from pathlib import Path

WORK_DIR = Path.home() / "Desktop" / "auto_annotate"
IMAGES_DIR = WORK_DIR / "input_images"
DATASETS_DIR = WORK_DIR / "datasets"
MODELS_DIR = WORK_DIR / "models"
ANNOTATIONS_DIR = WORK_DIR / "annotations"
YOLO_ANNOTATIONS_DIR = ANNOTATIONS_DIR / "yolo"
COCO_ANNOTATIONS_DIR = ANNOTATIONS_DIR / "coco"

NMS_IOU = 0.45
DEFAULT_CONF = 0.25

CANVAS_W = 800
CANVAS_H = 680
HANDLE_SIZE = 8
MIN_ZOOM = 0.1
MAX_ZOOM = 20.0
ZOOM_STEP_KEYBOARD = 1.2
ZOOM_STEP_SCROLL = 1.15

MIN_BOX_DRAW_PX = 5
MIN_BOX_RESIZE_PX = 3
NUDGE_PX = 1

CONF_SPINBOX_INCREMENT = 0.05
UNDO_DEPTH_MAX = 20

AUTOSAVE_DEBOUNCE_MS = 1500
AUTOSAVE_CEILING_MS = 30_000

TOOLTIP_DELAY_MS = 500

ENGINE_BUILD_WORKSPACE_GB = 1
ENGINE_BUILD_FP16_DEFAULT = True
ENGINE_BUILD_POLL_MS = 250

FRAME_EXTRACT_POLL_MS = 100
FRAME_EXTRACT_VIDEO_EXTS = (".mp4", ".mkv", ".webm")
FRAME_EXTRACT_JPG_QUALITY = 92

DEFAULT_SPLIT_TRAIN = 70
DEFAULT_SPLIT_VAL = 20
DEFAULT_SPLIT_TEST = 10
DEFAULT_SPLIT_SEED = 42
MIN_IMAGES_FOR_SPLIT = 2

CLASS_COLORS = [
    "#FF4444",
    "#44DD44",
    "#4488FF",
    "#FFEE00",
    "#FF44FF",
    "#00DDDD",
    "#FF8800",
    "#FF44AA",
    "#AA44FF",
    "#44FFAA",
    "#FF6644",
    "#44AAFF",
    "#FFAA44",
    "#44FF66",
    "#FF4488",
    "#88FF44",
]
